<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitXMLReporter -->
<testsuite hostname="DESKTOP-PN3ADTT" ignored="0" name="Test1" tests="6" failures="2" timestamp="05 Jun 2019 02:20:36 GMT" time="0.02" errors="0">
  <testcase name="f" time="0.0" classname="Package1.Testclass3"/>
  <testcase name="f1" time="0.004" classname="Package1.Testclass3">
    <failure type="java.lang.AssertionError" message="this is failed">
      <![CDATA[java.lang.AssertionError: this is failed
at Package1.Testclass3.f1(Testclass3.java:15)
... Removed 26 stack frames]]>
    </failure>
  </testcase> <!-- f1 -->
  <testcase name="f2" time="0.004" classname="Package1.Testclass3"/>
  <testcase name="f" time="0.0" classname="Package1.TestClass4"/>
  <testcase name="f1" time="0.0" classname="Package1.TestClass4">
    <failure type="java.lang.AssertionError" message="this is failed">
      <![CDATA[java.lang.AssertionError: this is failed
at Package1.TestClass4.f1(TestClass4.java:15)
... Removed 26 stack frames]]>
    </failure>
  </testcase> <!-- f1 -->
  <testcase name="f2" time="0.004" classname="Package1.TestClass4"/>
</testsuite> <!-- Test1 -->
